name: Extract GC I485 Data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '27 7 * * WED' # runs at every Wednesday 7:27am

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      #----------------------------------------------
      #  -----  install & configure uv  -----
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      #----------------------------------------------
      #       install dependencies with uv
      #----------------------------------------------
      - name: Install dependencies
        run: uv sync

      - name: Run i485 parser
        run: uv run python i485_parser.py

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
